# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc3707f3204c5ee6c4183d2ca02a9ce57082d5a9fcec217421688ae40eacb1dfcbbe7f5cc1980e7c7b0fc518b553616fa7f11f69eb809ebbfd26d7b22d07a45b

test:
  secret_key_base: 8a9258e6c0d72e58f051209915ae046da6af69864dd80adb65c4a4b6572033c03deb4204ad5c5dd439ded676ccc25862e32dadd9ff21d274e6d5c22995490cf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
